import type { UiTextCatalog } from "./catalogShape";

export const enUS: UiTextCatalog = {
  audit: {
    actions: {
      refreshAudit: "Refresh audit",
      return: "Return",
      viewAudit: "View audit",
    },
    detail: {
      actions: {
        backToList: "Back to list",
        openFile: "Open file",
        viewDiff: "View diff",
      },
      labels: {
        auditRecordDetail: "Audit record detail",
        disclosure: "Disclosure",
        effectiveConfiguration: "Effective configuration",
        evidenceVisibility: "Evidence visibility",
        hiddenReason: "Hidden reason",
        partialReason: "Partial reason",
        permissionReason: "Permission reason",
        rawPayload: "Raw payload",
        recordPayload: "Record payload",
        redactionReason: "Redaction reason",
        relatedLogs: "Related logs",
        reservedLinks: "Reserved links",
        sanitizedEvidence: "Sanitized evidence",
        sanitizedEvidencePayload: "Sanitized evidence payload",
        sanitizedRecordPayload: "Sanitized record payload",
        whatHappened: "What happened",
        whyItMatters: "Why it matters",
        workspaceEvidence: "Workspace evidence",
      },
      messages: {
        availableByPolicy: "Available by policy",
        configurationSummaryUnavailable:
          "Configuration summary is not available.",
        evidenceDetailLoadError: ({ message }) =>
          `Evidence detail could not be loaded: ${message}`,
        evidenceDetailLoading: "Loading evidence detail.",
        evidencePayloadTitle: ({ label }) => `Evidence payload · ${label}`,
        hiddenByDefault: "Hidden by default",
        hiddenByPermission: "Hidden by permission",
        hiddenByPolicy: "Hidden by policy",
        limited: "Limited",
        loadingCompleteRecordDetail: "Loading complete record detail.",
        noEvidenceForRecord: "No evidence is available for this record.",
        noPayloadAvailable: "No payload available",
        noRelatedLogLink: "No related log link is available yet.",
        noSanitizedPayloadForRecord:
          "No sanitized payload is available for this record.",
        payloadAvailableNotShown: "Payload available, not shown",
        recordDetailLoadError: ({ message }) =>
          `Record detail could not be loaded: ${message}`,
        recordEventSummary: ({ kind, source, time }) =>
          `${source} recorded a ${kind} event at ${time}.`,
        sanitizedPayloadShown: "Sanitized payload shown",
        visible: "Visible",
      },
    },
    empty: {
      noEvidence: "No evidence is available.",
    },
    labels: {
      audit: "Audit",
      auditEvidenceWorkspace: "Audit evidence workspace",
      auditOverview: "Audit Overview",
      auditRecordFilters: "Audit record filters",
      auditRecords: "Audit records",
      auditVerdictNotice: "Audit verdict notice",
      auditWorkflow: "Audit workflow",
      code: "Code",
      cursor: "Cursor",
      confidence: ({ value }) => `Confidence: ${value}`,
      evidenceRefCount: ({ count }) =>
        count === 1 ? "1 evidence ref" : `${count} evidence refs`,
      evidenceTimeline: "Evidence Timeline",
      evidence: "Evidence",
      filter: "Filter",
      filterCountsHelp: "Counts stay visible across scopes.",
      keyIssue: "Key issue",
      noMutations: "No mutations",
      project: "Project",
      productSubtitle: "Task-first Intelligent Workbench",
      readOnly: "Read-only",
      recordCount: ({ count }) => (count === 1 ? "1 record" : `${count} records`),
      recordFilters: "Record Filters",
      resyncSuggested: "Resync suggested",
      retryable: "Retryable",
      scope: ({ kind }) => `Scope: ${kind}`,
      sessionName: ({ name }) => `Session: ${name}`,
      session: "Session",
      task: "Task",
      taskAuthoring: "Task authoring",
      taskPlanningExecution: "Task Planning & Execution",
      trustPlane: "Trust plane",
      visibleRecords: "visible records",
    },
    boundary: {
      backend_busy: "Backend busy",
      empty: "Empty",
      fatal_error: "Fatal error",
      hidden_evidence: "Hidden evidence",
      loading: "Loading",
      partial: "Partial evidence",
      permission_denied: "Permission denied",
      ready: "Ready",
      recoverable_error: "Recoverable error",
      stale_resync: "Stale snapshot",
    },
    completeness: {
      complete: "Complete",
      failed: "Failed",
      hidden: "Hidden",
      not_started: "Not started",
      partial: "Partial",
      running: "Running",
    },
    filters: {
      actions: "Actions",
      all: "All records",
      config: "Config",
      confirmations: "Confirmations",
      files: "Files",
      logs: "Logs",
      results: "Results",
      risks: "Risks",
      system: "System",
    },
    liveStatus: {
      disconnectedMessage:
        "Manual refresh still works; this page may not update automatically.",
      disconnectedTitle: "Live audit updates unavailable",
      refreshingMessage: "Live audit stream is applying new records.",
      refreshingTitle: "Updating audit evidence",
      staleMessage:
        "Refreshing from source; current evidence remains readable.",
      staleTitle: "Audit snapshot may be stale",
    },
    messages: {
      auditRecordEmptyBody:
        "Audit evidence will appear here as the session produces records.",
      auditRecordEmptyTitle: "No audit records yet",
      evidenceTimelineHelp: "User-readable records from events and messages.",
      loadingAudit: "Reading audit records and evidence.",
      permissionLimited: "Permission limited",
      readOnlyTrustPlane:
        "Audit is a read-only trust plane. It explains what happened without changing the Task or session.",
      snapshotUnavailable: "Audit snapshot is not available.",
      unavailable: "Audit unavailable",
    },
    scopeStatus: ({ kind, status }) => `${kind} audit · ${status}`,
    actors: {
      agent: "agent",
      audit_agent: "audit agent",
      system: "system",
      tool: "tool",
      user: "user",
    },
    confidenceLevels: {
      high: "high",
      low: "low",
      medium: "medium",
      unknown: "unknown",
    },
    flags: {
      hidden: "Hidden",
      partial: "Partial",
      redacted: "Redacted",
      stale: "Stale",
    },
    recordKinds: {
      action: "action",
      audit_verdict: "audit verdict",
      config_change: "config change",
      confirmation: "confirmation",
      file_change: "file change",
      log_evidence: "log evidence",
      message: "message",
      observation: "observation",
      result: "result",
      risk: "risk",
      system: "system",
    },
    sourceLabels: {
      AuditAgent: "AuditAgent",
      EventStream: "EventStream",
      "Log archive": "Log archive",
      "Log archive manifest": "Log archive manifest",
      Workspace: "Workspace",
    },
    verdict: {
      failed: "Verdict: Failed",
      inconclusive: "Verdict: Inconclusive",
      not_available: "Verdict: Not available",
      passed: "Verdict: Passed",
      warning: "Verdict: Warning",
    },
    verdictNotice: {
      failed: "Audit found a blocking issue.",
      inconclusive: "Audit cannot establish confidence yet.",
      warning: "Audit found a non-blocking concern.",
    },
  },
  common: {
    actions: {
      cancel: "Cancel",
      close: "Close",
      retry: "Retry",
    },
    status: {
      creating: "Creating",
      disabled: "disabled",
      failed: "Failed",
      loading: "Loading",
      ready: "Ready",
    },
  },
  diagnostics: {
    actions: {
      exportBundle: "Export diagnostics",
      returnToAudit: "Return to audit",
      returnToSession: "Return to session",
    },
    labels: {
      auditRecord: "Audit record",
      bundle: "Bundle",
      bundleReady: "Bundle ready",
      diagnosticExportResult: "Diagnostic export result",
      diagnostics: "Diagnostics",
      exportBundle: "Export bundle",
      manifest: "Manifest",
      readOnly: "Read-only",
      redaction: "Redaction",
      session: "Session",
      task: "Task",
      zipPath: "Zip path",
    },
    messages: {
      contextUnavailable: "Diagnostic context is unavailable for this route.",
      exportBody:
        "Create a redacted local bundle for this session without exposing raw logs in the UI.",
      exportFailed: "Diagnostic export failed. Retry or use the CLI command.",
      fileCount: ({ count }) => (count === 1 ? "1 file" : `${count} files`),
      handoffReady: "Session log references are ready for local export.",
      includedSections: ({ sections }) => `Included sections: ${sections}.`,
      noSections: "none",
      sidecarRequired:
        "Start Plato with the local sidecar to export diagnostics from the UI.",
      warningCount: ({ count }) =>
        `${count === 1 ? "1 warning" : `${count} warnings`} recorded in the manifest.`,
    },
  },
  main: {
    activity: {
      actions: {
        backToActivity: "Back to activity",
        close: "Close",
        openAudit: "Open audit",
        openDiagnostic: "Open diagnostic",
        openFiles: "Open files",
        openPlan: "Open plan",
        openResult: "Open result",
        openTask: "Open task",
        retry: "Retry",
        viewFullResult: "View full result",
      },
      descriptions: {
        focusedOnTask: ({ title }) => `Focused on ${title}.`,
        loadError: "Plato could not load the activity timeline.",
        loading: "Loading activity.",
        noMatchingWithTask: "Try another filter or return to the selected task.",
        noMatchingWithoutTask: "Try another filter or close this view.",
        sessionUpdates: "All session updates.",
      },
      filters: {
        all: "All",
        currentTask: "Current task",
        errors: "Errors",
        results: "Results",
      },
      labels: {
        activity: "Activity",
        activityCount: ({ count }) => `Activity ${count}`,
        allActivity: "All activity",
        currentTask: "Current task",
        disclosure: "Disclosure",
        effect: "Effect",
        evidence: "Evidence",
        filterControls: "Activity filters",
        fullResult: "Full result",
        loadingActivity: "Loading activity",
        noMatchingActivity: "No matching activity",
        scopePlan: "Plan",
        scopeSession: "Session",
        scopeTask: "Task",
        sessionActivity: "Session activity",
        source: "Source",
        taskUpdates: "Task updates",
      },
      kinds: {
        answer: "Answer",
        askAnswered: "ASK answered",
        askAsked: "ASK asked",
        confirmationRequested: "Confirmation requested",
        confirmationResolved: "Confirmation resolved",
        executionUpdate: "Execution update",
        fileSummary: "File summary",
        guidanceRecorded: "Guidance recorded",
        planUpdated: "Plan updated",
        recoveryNote: "Recovery note",
        resultReady: "Result ready",
        routerInterpretation: "Router interpretation",
        taskChanged: "Task changed",
        taskCreated: "Task created",
        taskRemoved: "Task removed",
        userInput: "User input",
      },
      sideEffects: {
        authorizationEffect: "Needs confirmation",
        contextEffect: "Context updated",
        evidenceEffect: "Evidence updated",
        executionRequest: "Execution requested",
        noEffect: "No workspace change",
        resumeEffect: "Waiting to resume",
        stateEffect: "System state updated",
      },
    },
    detail: {
      actions: {
        archivePlan: "Archive plan",
        archivingPlan: "Archiving...",
        backToConversation: "Back to conversation",
        backToSummary: "Back to summary",
        collapse: "Collapse",
        openArchivedPlan: "Open archived plan from Conversation",
        openFile: "Open file",
        openPlanProgress: ({ title }) => `Open Plan & Progress: ${title}`,
        openSessionActivity: "Open session activity",
        openTaskUpdates: "Open task updates",
        retry: "Retry",
        retrying: "Retrying",
        stop: "Stop",
        stopping: "Stopping",
        viewDiff: "View diff",
        viewAudit: "View audit",
        viewFileChanges: "View file changes",
        viewResult: "View result",
      },
      labels: {
        acceptanceCriteria: "Acceptance criteria",
        archivedPlanProgressWorkspace: "Archived Plan & Progress workspace",
        changedFiles: "Changed files",
        conversation: "Conversation",
        detailed: "Detailed",
        details: "Details",
        fileChanges: "File changes",
        fullResult: "Full result",
        includesChildTasks: "Includes child tasks",
        intent: "Intent",
        instructions: "Instructions",
        latestActivity: "Latest activity",
        plan: "Plan",
        planInteraction: "Plan interaction",
        planProgress: "Plan & Progress",
        planProgressWorkspace: "Plan & Progress workspace",
        planTarget: "plan",
        resultSummary: "Result summary",
        resizeDetailsPanel: "Resize details panel",
        routerDispatch: "Dispatch",
        routerIntent: "Intent",
        routerOutcome: "Outcome",
        routerScope: "Scope",
        selectedTaskTarget: "selected task",
        sessionActivity: "Session activity",
        sessionTarget: "session",
        summary: "Summary",
        taskActions: "Task actions",
        taskActivity: "Task activity",
        taskDetails: "Task details",
        taskInput: "Task input",
        taskTarget: ({ index }) => `Task ${index}`,
        userAction: "Action",
        userLabel: "Input",
        userYou: "You",
        workspaceChanges: "Workspace changes",
      },
      messages: {
        answerPlaceholder: "Answer in the input box.",
        conversationEmpty: "No conversation yet",
        fileCount: ({ count }) => (count === 1 ? "1 file" : `${count} files`),
        fileCountChanged: ({ count }) =>
          count === 1 ? "1 file changed." : `${count} files changed.`,
        confirmationResolution: {
          confirmed:
            "The confirmation was accepted. Plato can continue from this task.",
          revise:
            "A revision request was captured. Task-scoped input now refines this task.",
          skipped:
            "The confirmation was skipped. Plato will not perform this action.",
        },
        fullResultAvailable: "Full result available.",
        guidancePlaceholderPlan: "Ask Plato to refine the overall plan.",
        guidancePlaceholderSession:
          "Describe the goal or add guidance for this session.",
        guidancePlaceholderTask: "Add guidance for this task.",
        planInteractionBody:
          "Input now refines the whole plan. Select a task to inspect or guide one Task.",
        sectionsAvailable: ({ count }) =>
          count === 1 ? "1 section available." : `${count} sections available.`,
        taskCount: ({ count }) => (count === 1 ? "1 task" : `${count} tasks`),
      },
      fileChangeTypes: {
        created: "Created",
        deleted: "Deleted",
        modified: "Modified",
        renamed: "Renamed",
      },
      resultSectionKinds: {
        link: "link",
        list: "list",
        metric: "metric",
        text: "text",
      },
      status: {
        auditVerdict: {
          failed: "Failed",
          inconclusive: "Inconclusive",
          not_available: "Not available",
          passed: "Passed",
          warning: "Warning",
        },
        confirmation: {
          expired: "Expired",
          pending: "Waiting",
          resolved: "Confirmed",
        },
        eventConnection: {
          connected: "Events live",
          disconnected: "Events offline",
          resyncing: "Resyncing",
        },
        execution: {
          cancelled: "Cancelled",
          done: "Done",
          failed: "Failed",
          not_started: "Not started",
          pending: "Queued",
          running: "Running",
          unknown: "Unknown",
          waiting_for_user: "Waiting",
        },
        messageKind: {
          actionable: "Needs reply",
          error: "Error",
          informational: "Update",
          response: "Result",
        },
        planning: {
          assessing: "Understanding",
          awaiting_user: "Waiting for user",
          cancelled: "Cancelled",
          capturing_input: "Capturing input",
          draft_ready: "Draft ready",
          empty: "New session",
          published: "Published",
          ready_to_plan: "Ready to plan",
          rejected: "Rejected",
          unknown: "Unknown",
        },
        readiness: {
          accepted: "Accepted",
          cancelled: "Cancelled",
          draft: "Draft",
          published: "Published",
          unknown: "Unknown",
        },
        primaryExecutionRunning: "Executing",
        readOnly: "Read-only",
        session: {
          completed: "Completed",
          draft_ready: "Draft ready",
          failed: "Failed",
          new: "New session",
          running: "Running",
          understanding: "Understanding",
          waiting_user: "Waiting for user",
        },
        stale: "Stale",
        stopping: "Stopping",
        taskNode: {
          cancelled: "Cancelled",
          done: "Done",
          draft: "Draft",
          failed: "Failed",
          queued: "Queued",
          running: "Running",
          waiting_user: "Waiting",
        },
        taskTree: {
          completed: "completed",
          draft: "draft",
          failed: "failed",
          published: "published",
          running: "running",
        },
      },
    },
    actions: {
      createSession: "New session",
      copySessionId: "Copy session ID",
      deleteSession: "Delete session",
      newSession: "New",
      openSession: "Open session",
      publishPlan: "Publish plan",
      renameSession: "Rename session",
      repairAuthoringState: "Repair authoring state",
    },
    empty: {
      createFirstSessionBody:
        "This workspace has no sessions yet. Create one when you are ready to start.",
      createFirstSessionTitle: "Create your first session",
      noPlanBody: "Describe a goal. Plato will draft a task plan for review.",
      noPlanTitle: "No task plan yet",
    },
    input: {
      contextMessageAriaLabel: "Context message",
      sendMessageAriaLabel: "Send message",
      writingToPrefix: "Writing to",
      writingTo: ({ target }) => `Writing to ${target}`,
    },
    interaction: {
      ask: {
        actions: {
          answer: "Answer",
          answering: "Answering",
          cancelQuestion: "Cancel question",
          cancelling: "Cancelling",
          defer: "Defer",
          deferring: "Deferring",
          submitAllAnswers: "Submit all answers",
          submittingAllAnswers: "Submitting answers",
          viewInConversation: "View in Conversation",
        },
        labels: {
          answerText: "Answer text",
          optional: "optional",
          planningQuestions: "Planning questions",
          question: ({ index }) => `Question ${index}`,
          selectedAnswer: "Selected answer",
          selectedOption: "Selected",
          task: ({ title }) => `Task: ${title}`,
          taskInputRequired: "Task input required",
        },
        messages: {
          addMissingInformation: "Add the missing information.",
          addYourAnswer: "Add your answer.",
          batchAnswerHeader: "Batch ASK answers:",
          batchAnswerItem: ({ answer, index, question }) =>
            `${index}. ${question}\nAnswer: ${answer}`,
          chooseOption: "Choose an option before submitting.",
          chooseOptionOrEnterAnswer: "Choose an option or enter an answer.",
          enterAnswer: "Enter an answer before submitting.",
          requiredQuestions: "Answer the required questions before submitting.",
          staleAsk:
            "This question no longer matches the selected task. Refresh or select the waiting task before answering.",
        },
        statuses: {
          answered: "Answered",
          cancelled: "Cancelled",
          deferred: "Deferred",
          expired: "Expired",
          pending: "Waiting",
          superseded: "Superseded",
        },
      },
      confirmation: {
        actions: {
          confirm: "Confirm",
          resolveDecision: "Resolve decision",
          resolving: "Resolving",
          reviseTask: "Revise task",
          skip: "Skip",
        },
        labels: {
          confirmationStatus: ({ status }) => `Confirmation ${status}`,
          decisionNeeded: "Decision needed",
          decisionUnavailable: "Decision unavailable",
          impact: "Impact",
          resolvingDecision: "Resolving decision",
        },
        messages: {
          decisionReadOnly: "This decision is read-only.",
          executionWaits: "Execution waits for this decision.",
          selectOneOption: "Select one confirmation option.",
        },
        statuses: {
          expired: "expired",
          pending: "pending",
          resolved: "resolved",
        },
      },
    },
    labels: {
      noSessions: "No sessions",
      noSessionSelected: "No session selected",
      sessionActions: "Session actions",
      sessionName: ({ name }) => `Session: ${name}`,
      taskWorkspace: "Task workspace",
      workspaceSessions: "Workspace sessions",
    },
    plan: {
      defaultTitle: "Task Tree",
      generatingBody:
        "Plato is understanding your goal and shaping the first task plan.",
      generatingTitle: "Generating task plan",
      overviewLabel: "Plan overview",
      overviewPrepared: "Plan overview is being prepared.",
      overviewSummary: ({ count, remainingCount, titles }) => {
        const suffix = remainingCount > 0 ? `, and ${remainingCount} more` : "";
        return `${count}-task plan covering ${titles}${suffix}.`;
      },
      taskCount: ({ count }) =>
        count === 1 ? "1 task in this plan" : `${count} tasks in this plan`,
    },
    repair: {
      authoringStateNeedsRepair: "Authoring state needs repair",
      repairing: "Repairing",
    },
    sessionDialog: {
      createFormAriaLabel: "Create session form",
      createTitle: "Create session",
      deleteConfirmationAriaLabel: "Delete session confirmation",
      deleteConfirmationBody: ({ name }) =>
        `Delete session "${name}"? Plato will archive this session and switch to the next available one.`,
      deleteTitle: "Delete session?",
      deleting: "Deleting",
      renameFormAriaLabel: "Rename session form",
      renameTitle: "Rename session",
      renaming: "Renaming",
      sessionName: "Session name",
    },
    states: {
      creatingSession: "Creating",
      creatingSessionFull: "Creating session",
      loadError: "Load error",
      openingSessionBody: "Plato is preparing this workspace.",
      openingSessionTitle: "Opening session",
      publishingPlan: "Publishing plan",
      unableToOpenSessionBody:
        "Plato could not load this session. Refresh the page or choose another session.",
      unableToOpenSessionTitle: "Unable to open session",
      workspaceSwitchFailed: "Could not open that workspace.",
      workspaceSwitchUnavailable:
        "Workspace switching is only available in the Plato desktop app.",
      workspaceSwitching: "Switching workspace.",
    },
  },
  productError: {
    recoveryAriaLabel: "Suggested recovery actions",
    recovery: {
      answer_ask: {
        description: "Answer the pending question before continuing.",
        label: "Answer question",
      },
      edit_input: {
        description: "Change the input and submit again.",
        label: "Edit input",
      },
      export_diagnostics: {
        description: "Export a redacted diagnostic bundle.",
        label: "Export diagnostics",
      },
      none: {
        description: "No safe product recovery action is available.",
        label: "No safe recovery action",
      },
      open_audit: {
        description: "Inspect Audit evidence for the affected session or task.",
        label: "View audit",
      },
      open_settings: {
        description: "Open local provider settings.",
        label: "Open settings",
      },
      open_macos_privacy_accessibility: {
        description:
          "Open macOS Privacy & Security settings and grant Accessibility permission to the helper.",
        label: "Open Accessibility settings",
      },
      open_macos_privacy_automation: {
        description:
          "Open macOS Privacy & Security settings and grant Automation permission to the helper.",
        label: "Open Automation settings",
      },
      refresh_snapshot: {
        description: "Refresh the session view to get the latest state.",
        label: "Refresh session",
      },
      rerun_readiness_check: {
        description: "Run the local computer-use readiness check again.",
        label: "Recheck readiness",
      },
      restart_helper: {
        description: "Restart Plato Computer Use Helper after changing permissions.",
        label: "Restart helper",
      },
      retry_command: {
        description: "Run the command again after resolving the issue.",
        label: "Retry command",
      },
      retry_task: {
        description: "Retry the affected task when retry is available.",
        label: "Retry task",
      },
      wait_for_events: {
        description: "Wait for sidecar events before taking another action.",
        label: "Wait for updates",
      },
    },
  },
  usage: {
    actions: {
      openUsage: "Usage",
      return: "Return",
    },
    dimensions: {
      plan: "Plans",
      session: "Sessions",
      task: "Tasks",
      workspace: "Workspace",
    },
    dimensionHelp: {
      plan: "Plan-level usage for the selected session when available.",
      session: "Session totals across this workspace.",
      task: "Task-level usage for calls that can be attributed to a Task.",
      workspace: "All tracked provider calls for this workspace.",
    },
    labels: {
      cacheHitRate: "Cache hit rate",
      calls: "Calls",
      inputOutput: "Input / output",
      reasoningTokens: "Reasoning tokens",
      tokenUsage: "Token usage",
      tokenUsageBudget: "Budget",
      totalTokens: "Total tokens",
      unknownUsage: "Unknown usage",
      usage: "Usage",
      workspaceId: ({ id }) => `workspace ${id}`,
    },
    messages: {
      compactHelp: "Tracked provider usage for this scope.",
      highUsageWarning: "High usage",
      highUsageWarningTitle: ({ threshold }) =>
        `This scope has reached at least ${threshold} tokens. Review usage before continuing long-running work.`,
      workspaceUsageHelp:
        "Compare token usage by Workspace, Session, Plan, and Task. Raw prompts and completions are never shown here.",
    },
    states: {
      cacheUnavailable: "Cache unavailable",
      noBreakdownRows: "No breakdown rows for this filter.",
      noUsageTracked: "No token usage tracked yet.",
      notReported: "Not reported",
      routeUnavailable: "Usage route unavailable",
      routeUnavailableBody: "Usage context is unavailable for this route.",
      sidecarRequired: "Token usage requires the local sidecar.",
      summaryUnavailable: "Token usage summary is unavailable.",
    },
  },
  settings: {
    actions: {
      configureSettings: "Configure settings",
      continueToMainPage: "Continue to Main Page",
      closeSettings: "Close settings",
      exportDiagnostics: "Export diagnostics",
      exportingDiagnostics: "Exporting diagnostics",
      openSettings: "Open Settings",
      retryCheck: "Retry check",
      retryLoad: "Retry load",
      return: "Return",
      saveAndCheck: "Save and check",
    },
    fields: {
      apiKey: "API key",
      bundle: "Bundle",
      defaultProfile: "Default profile",
      diagnostics: "Diagnostics",
      gitAvailability: "Git availability",
      initializeGitForOpenedWorkspaces: "Initialize Git for opened workspaces",
      interfaceLanguage: "Interface language",
      logging: "Logging",
      loggingProfile: "Logging profile",
      model: "Model",
      provider: "Provider",
      readiness: "Readiness",
      webFetch: "Web Page Fetch",
      webFetchMaxCharsPerUrl: "Fetch chars per URL",
      webFetchMaxTotalChars: "Fetch total chars",
      webFetchMaxUrls: "Fetch URL limit",
      webSearch: "Web Search",
      webSearchApiKey: "Web Search API key",
      webSearchMaxResults: "Result limit",
      webSearchMode: "Search mode",
      webSearchProvider: "Search provider",
      webSearchStatus: "Web search status",
    },
    labels: {
      blockingIssues: "Blocking issues",
      checkingSetup: "Checking setup",
      completeFirstRunSetup: "Complete first-run setup",
      computerUseAccessibility: "Accessibility trusted",
      computerUseBackend: "Backend",
      computerUseExecutable: "Effective executable",
      computerUseFailureKind: "Failure kind",
      computerUseHelperApp: "Helper app",
      computerUseReadiness: "Computer-use readiness",
      computerUseRecoveryActions: "Recovery actions",
      computerUseSignature: "Helper signature",
      computerUseStatus: "Status",
      configured: "configured",
      degradedReady: "Global setup is ready with warnings.",
      diagnosticsAvailable: "bundle export available",
      diagnosticsUnavailable: "bundle export unavailable",
      editable: "Editable",
      firstRun: "First run",
      firstRunReady: "First-run setup is ready.",
      gitAvailable: "Git available",
      gitFailed: "Git check failed",
      gitMissing: "Git not found",
      localSetup: "Global setup",
      missing: "missing",
      missingEnvironmentVariables: "Missing environment variables",
      noDiagnosticSession: "No session is available for diagnostics export yet.",
      notChecked: "not checked",
      notCreated: "Not created",
      readinessIssues: "Readiness issues",
      readinessResult: "Readiness result",
      recommendedActions: "Recommended actions",
      setupCheckUnavailable: "Setup check unavailable",
      setupRequired: "Setup required",
      setupWarning: "Setup warning",
      settings: "Settings",
      settingsSetupForm: "Settings setup form",
      settingsUnavailable: "Settings unavailable",
      sidecarRequired: "Sidecar required",
      webSearchReady: "web search ready",
      warnings: "Warnings",
      workspaceGit: "Workspace Git",
      zipPath: "Zip path",
    },
    messages: {
      apiKeyConfigured: ({ source }) =>
        `Configured via ${source}; leave empty to keep it.`,
      apiKeyRequired: ({ hint }) => `Required: ${hint}.`,
      checkingReadiness: "Checking readiness.",
      checkingSidecarReadiness: "Checking local sidecar readiness.",
      checkingGitAvailability: "Checking Git availability.",
      diagnosticExportFailed: "Diagnostic export failed.",
      diagnosticExportHelp:
        "Export a redacted local bundle when setup still fails and a session is available.",
      gitAvailable: ({ version }) => `Git available: ${version}`,
      gitFailedHelp: "Plato could not verify Git availability on this machine.",
      gitMissingHelp:
        "Install Git to enable automatic initialization for new workspaces.",
      initializeGitForOpenedWorkspacesHelp:
        "When enabled, Plato runs git init for plain folders you open or switch to and adds .plato/ to the repository's local exclude file.",
      loadingSettings: "Loading settings",
      loadingSettingsHelp: "Loading local sidecar settings.",
      localSetupReadyWithWarnings: "Global setup is ready with warnings.",
      noReadinessReport:
        "The local sidecar did not return a readiness report.",
      noDiagnosticSession: "No session is available for diagnostics export yet.",
      readinessRecheckFailed: "Readiness recheck failed.",
      saveFailed: "Settings save failed.",
      saved: "Settings saved.",
      saving: "Saving settings.",
      settingsContractUnavailable:
        "The local sidecar did not return the settings config contract.",
      settingsDescription:
        "Configure Plato's global local LLM setup. It applies across workspaces.",
      settingsUnavailableHelp:
        "Start Plato in local sidecar HTTP mode to edit Product 1.0 settings.",
      setupRequiredBody:
        "Plato needs local LLM configuration before it can run the Main Page workflow.",
      webSearchApiKeyConfigured: ({ source }) =>
        `Configured via ${source}; leave empty to keep it.`,
      webSearchApiKeyRequired: ({ hint }) => `Required when enabled: ${hint}.`,
      webFetchDescription:
        "Allows execution Agents to extract bounded text from selected public source URLs.",
      webSearchDescription:
        "Allows execution Agents to search current public sources as external evidence.",
      workspaceGitDesktopUnavailable:
        "Workspace Git initialization is available in the Plato desktop app.",
    },
    localeOptions: {
      "en-US": "English",
      "zh-CN": "简体中文",
    },
    recovery: {
      answer_ask: "Answer the pending question.",
      edit_input: "Edit the current input.",
      export_diagnostics: "Export a redacted diagnostic bundle.",
      none: "No recovery action is available.",
      open_audit: "Inspect Audit evidence.",
      open_settings: "Configure local provider settings.",
      open_macos_privacy_accessibility:
        "Open macOS Accessibility permissions for the helper.",
      open_macos_privacy_automation:
        "Open macOS Automation permissions for the helper.",
      refresh_snapshot: "Retry after configuration changes.",
      rerun_readiness_check: "Recheck local computer-use readiness.",
      restart_helper: "Restart Plato Computer Use Helper.",
      retry_command: "Retry after configuration changes.",
      retry_task: "Retry the affected Task.",
      wait_for_events: "Wait for sidecar events before retrying.",
    },
    tabs: {
      configuration: "Configuration",
      dataManagement: "Data Management",
      runtimeBehavior: "Runtime Behavior",
      usageInformation: "Usage Information",
    },
  },
  workspace: {
    actions: {
      archiveWorkspace: "Archive workspace",
      cancelDelete: "Cancel",
      confirmDeletePlatoData: "Delete Plato data",
      deletePlatoData: "Delete Plato data",
      openWorkspaceMenu: "Open workspace actions",
      openOrAddWorkspace: "Open or add workspace",
      restoreWorkspace: "Restore workspace",
      workspaceManagement: "Workspace Management",
    },
    labels: {
      activeWorkspaces: "Active workspaces",
      archived: "Archived",
      archivedWorkspaces: "Archived workspaces",
      dataManagement: "Data Management",
      deletePlatoData: "Delete Plato data",
      workspace: "Workspace",
      workspaceManagement: "Workspace Management",
      workspaces: "Workspaces",
    },
    messages: {
      archiveHelp: "Archive hides a workspace from Main Page without deleting files.",
      bridgeUnavailable:
        "Workspace management is available in the Plato desktop app.",
      deletePlatoDataConfirmation: ({ name }) =>
        `Delete Plato data for ${name}? Project files and the workspace folder are kept.`,
      deletePlatoDataHelp:
        "Deletes Plato-owned .plato data and legacy metadata roots. Project files are not deleted.",
      lifecycleActionFailed: "Workspace action failed.",
      loadingWorkspaces: "Loading workspaces.",
      noArchivedWorkspaces: "No archived workspaces.",
      noWorkspaceData: "No workspace data is available.",
      restoreHelp: "Restore makes an archived workspace visible again.",
    },
  },
  workspaceInspection: {
    actions: {
      openFile: "Open file",
      refresh: "Refresh",
      return: "Return",
      viewDiff: "View diff",
    },
    labels: {
      captured: "captured",
      changed: "Changed",
      changedFiles: "Changed files",
      clean: "Clean",
      diff: "Diff",
      fileContent: "File content",
      file: "File",
      fileDiff: "File diff",
      fileViewer: "File viewer",
      gitStatus: "Git status",
      inspectionViews: "Inspection views",
      live: "live",
      localToolFiles: "Local tool files",
      mixed: "Mixed",
      repository: "Repository",
      staged: "Staged",
      truncated: "truncated",
      unstaged: "Unstaged",
      untracked: "Untracked",
      workspaceInspection: "Workspace inspection",
    },
    states: {
      cleanBody: "No changed files in this workspace.",
      diffUnavailable: ({ reason }) => `Diff is unavailable: ${reason}.`,
      diffUnavailableTitle: "Diff unavailable",
      fileUnavailable: ({ reason }) =>
        `File cannot be rendered as text: ${reason}.`,
      fileUnavailableTitle: "File unavailable",
      inspectionFailed: "Workspace inspection failed.",
      inspectionUnavailable: "Inspection unavailable",
      inspectionRouteUnavailable: "Inspection route unavailable",
      inspectionRouteUnavailableBody:
        "Inspection context is unavailable for this route.",
      loading: "Loading workspace inspection",
      localNoiseSuppressed: ({ count }) =>
        `${count} local system file${count === 1 ? "" : "s"} hidden from the inspection list.`,
      readOnly: "Read-only workspace inspection.",
      requiresSidecar: "Workspace inspection requires the local sidecar.",
      statusUnavailable: "Status unavailable.",
    },
  },
};
