import type { UiTextCatalog } from "./catalogShape";

export const zhCN: UiTextCatalog = {
  audit: {
    actions: {
      refreshAudit: "刷新审计",
      return: "返回",
      viewAudit: "查看审计",
    },
    detail: {
      actions: {
        backToList: "返回列表",
        openFile: "打开文件",
        viewDiff: "查看 Diff",
      },
      labels: {
        auditRecordDetail: "审计记录详情",
        disclosure: "披露范围",
        effectiveConfiguration: "生效配置",
        evidenceVisibility: "证据可见性",
        hiddenReason: "隐藏原因",
        partialReason: "部分证据原因",
        permissionReason: "权限原因",
        rawPayload: "原始载荷",
        recordPayload: "记录载荷",
        redactionReason: "脱敏原因",
        relatedLogs: "相关日志",
        reservedLinks: "保留链接",
        sanitizedEvidence: "脱敏证据",
        sanitizedEvidencePayload: "脱敏证据载荷",
        sanitizedRecordPayload: "脱敏记录载荷",
        whatHappened: "发生了什么",
        whyItMatters: "为什么重要",
        workspaceEvidence: "工作区证据",
      },
      messages: {
        availableByPolicy: "按策略可用",
        configurationSummaryUnavailable: "配置摘要不可用。",
        evidenceDetailLoadError: ({ message }) => `证据详情加载失败：${message}`,
        evidenceDetailLoading: "正在加载证据详情。",
        evidencePayloadTitle: ({ label }) => `证据载荷 · ${label}`,
        hiddenByDefault: "默认隐藏",
        hiddenByPermission: "因权限隐藏",
        hiddenByPolicy: "因策略隐藏",
        limited: "受限",
        loadingCompleteRecordDetail: "正在加载完整记录详情。",
        noEvidenceForRecord: "此记录暂无可用证据。",
        noPayloadAvailable: "暂无可用载荷",
        noRelatedLogLink: "暂无相关日志链接。",
        noSanitizedPayloadForRecord: "此记录暂无可用脱敏载荷。",
        payloadAvailableNotShown: "载荷可用，未展示",
        recordDetailLoadError: ({ message }) => `记录详情加载失败：${message}`,
        recordEventSummary: ({ kind, source, time }) =>
          `${source} 在 ${time} 记录了 ${kind} 事件。`,
        sanitizedPayloadShown: "已展示脱敏载荷",
        visible: "可见",
      },
    },
    empty: {
      noEvidence: "暂无可用证据。",
    },
    labels: {
      audit: "审计",
      auditEvidenceWorkspace: "审计证据工作区",
      auditOverview: "审计概览",
      auditRecordFilters: "审计记录筛选",
      auditRecords: "审计记录",
      auditVerdictNotice: "审计结论提示",
      auditWorkflow: "审计工作流",
      code: "代码",
      cursor: "游标",
      confidence: ({ value }) => `置信度：${value}`,
      evidenceRefCount: ({ count }) => `${count} 个证据引用`,
      evidenceTimeline: "证据时间线",
      evidence: "证据",
      filter: "筛选",
      filterCountsHelp: "各范围的计数会持续显示。",
      keyIssue: "关键问题",
      noMutations: "无修改",
      project: "项目",
      productSubtitle: "任务优先智能工作台",
      readOnly: "只读",
      recordCount: ({ count }) => `${count} 条记录`,
      recordFilters: "记录筛选",
      resyncSuggested: "建议重新同步",
      retryable: "可重试",
      scope: ({ kind }) => `范围：${kind}`,
      sessionName: ({ name }) => `会话：${name}`,
      session: "会话",
      task: "任务",
      taskAuthoring: "任务编排",
      taskPlanningExecution: "任务规划与执行",
      trustPlane: "信任平面",
      visibleRecords: "可见记录",
    },
    boundary: {
      backend_busy: "后端繁忙",
      empty: "为空",
      fatal_error: "严重错误",
      hidden_evidence: "隐藏证据",
      loading: "加载中",
      partial: "部分证据",
      permission_denied: "权限不足",
      ready: "就绪",
      recoverable_error: "可恢复错误",
      stale_resync: "快照过期",
    },
    completeness: {
      complete: "完整",
      failed: "失败",
      hidden: "隐藏",
      not_started: "未开始",
      partial: "部分",
      running: "运行中",
    },
    filters: {
      actions: "操作",
      all: "全部记录",
      config: "配置",
      confirmations: "确认",
      files: "文件",
      logs: "日志",
      results: "结果",
      risks: "风险",
      system: "系统",
    },
    liveStatus: {
      disconnectedMessage: "仍可手动刷新；此页面可能不会自动更新。",
      disconnectedTitle: "实时审计更新不可用",
      refreshingMessage: "实时审计流正在应用新记录。",
      refreshingTitle: "正在更新审计证据",
      staleMessage: "正在从来源刷新；当前证据仍可读取。",
      staleTitle: "审计快照可能已过期",
    },
    messages: {
      auditRecordEmptyBody: "会话产生审计记录后会显示在这里。",
      auditRecordEmptyTitle: "暂无审计记录",
      evidenceTimelineHelp: "来自事件和消息的用户可读记录。",
      loadingAudit: "正在读取审计记录和证据。",
      permissionLimited: "权限受限",
      readOnlyTrustPlane:
        "审计是只读信任平面。它解释发生了什么，不会修改任务或会话。",
      snapshotUnavailable: "审计快照不可用。",
      unavailable: "审计不可用",
    },
    scopeStatus: ({ kind, status }) => `${kind} 审计 · ${status}`,
    actors: {
      agent: "智能体",
      audit_agent: "审计智能体",
      system: "系统",
      tool: "工具",
      user: "用户",
    },
    confidenceLevels: {
      high: "高",
      low: "低",
      medium: "中",
      unknown: "未知",
    },
    flags: {
      hidden: "已隐藏",
      partial: "部分证据",
      redacted: "已脱敏",
      stale: "可能过期",
    },
    recordKinds: {
      action: "操作",
      audit_verdict: "审计结论",
      config_change: "配置变更",
      confirmation: "确认",
      file_change: "文件变更",
      log_evidence: "日志证据",
      message: "消息",
      observation: "观测",
      result: "结果",
      risk: "风险",
      system: "系统",
    },
    sourceLabels: {
      AuditAgent: "审计智能体",
      EventStream: "事件流",
      "Log archive": "日志归档",
      "Log archive manifest": "日志归档清单",
      Workspace: "工作区",
    },
    verdict: {
      failed: "结论：失败",
      inconclusive: "结论：尚无定论",
      not_available: "结论：不可用",
      passed: "结论：通过",
      warning: "结论：警告",
    },
    verdictNotice: {
      failed: "审计发现阻塞问题。",
      inconclusive: "审计尚无法建立足够信心。",
      warning: "审计发现非阻塞问题。",
    },
  },
  common: {
    actions: {
      cancel: "取消",
      close: "关闭",
      retry: "重试",
    },
    status: {
      creating: "创建中",
      disabled: "已禁用",
      failed: "失败",
      loading: "加载中",
      ready: "就绪",
    },
  },
  diagnostics: {
    actions: {
      exportBundle: "导出诊断",
      returnToAudit: "返回审计",
      returnToSession: "返回会话",
    },
    labels: {
      auditRecord: "审计记录",
      bundle: "诊断包",
      bundleReady: "诊断包已就绪",
      diagnosticExportResult: "诊断导出结果",
      diagnostics: "诊断",
      exportBundle: "导出诊断包",
      manifest: "Manifest",
      readOnly: "只读",
      redaction: "脱敏",
      session: "会话",
      task: "任务",
      zipPath: "Zip 路径",
    },
    messages: {
      contextUnavailable: "此路由缺少诊断上下文。",
      exportBody:
        "为此会话创建已脱敏的本地诊断包，不在 UI 中暴露原始日志。",
      exportFailed: "诊断导出失败。请重试或使用 CLI 命令。",
      fileCount: ({ count }) => `${count} 个文件`,
      handoffReady: "会话日志引用已准备好，可在本地导出。",
      includedSections: ({ sections }) => `包含区段：${sections}。`,
      noSections: "无",
      sidecarRequired: "请使用本地 sidecar 启动 Plato 后再从 UI 导出诊断。",
      warningCount: ({ count }) => `Manifest 中记录了 ${count} 个警告。`,
    },
  },
  main: {
    activity: {
      actions: {
        backToActivity: "返回活动",
        close: "关闭",
        openAudit: "打开审计",
        openDiagnostic: "打开诊断",
        openFiles: "打开文件",
        openPlan: "打开计划",
        openResult: "打开结果",
        openTask: "打开任务",
        retry: "重试",
        viewFullResult: "查看完整结果",
      },
      descriptions: {
        focusedOnTask: ({ title }) => `聚焦于 ${title}。`,
        loadError: "Plato 无法加载活动时间线。",
        loading: "正在加载活动。",
        noMatchingWithTask: "尝试其他筛选，或返回当前选中的任务。",
        noMatchingWithoutTask: "尝试其他筛选，或关闭此视图。",
        sessionUpdates: "全部会话活动。",
      },
      filters: {
        all: "全部",
        currentTask: "当前任务",
        errors: "错误",
        results: "结果",
      },
      labels: {
        activity: "活动",
        activityCount: ({ count }) => `活动 ${count}`,
        allActivity: "全部活动",
        currentTask: "当前任务",
        disclosure: "披露",
        effect: "影响",
        evidence: "证据",
        filterControls: "活动筛选",
        fullResult: "完整结果",
        loadingActivity: "正在加载活动",
        noMatchingActivity: "没有匹配的活动",
        scopePlan: "计划",
        scopeSession: "会话",
        scopeTask: "任务",
        sessionActivity: "会话活动",
        source: "来源",
        taskUpdates: "任务动态",
      },
      kinds: {
        answer: "回答",
        askAnswered: "ASK 已回答",
        askAsked: "ASK 提问",
        confirmationRequested: "请求确认",
        confirmationResolved: "确认已处理",
        executionUpdate: "执行更新",
        fileSummary: "文件摘要",
        guidanceRecorded: "指导已记录",
        planUpdated: "计划已更新",
        recoveryNote: "恢复提示",
        resultReady: "结果已就绪",
        routerInterpretation: "路由解释",
        taskChanged: "任务已变更",
        taskCreated: "任务已创建",
        taskRemoved: "任务已移除",
        userInput: "用户输入",
      },
      sideEffects: {
        authorizationEffect: "需要确认",
        contextEffect: "上下文已更新",
        evidenceEffect: "证据已更新",
        executionRequest: "已请求执行",
        noEffect: "未改变工作区",
        resumeEffect: "等待恢复",
        stateEffect: "系统状态已更新",
      },
    },
    detail: {
      actions: {
        archivePlan: "归档计划",
        archivingPlan: "正在归档...",
        backToConversation: "返回对话",
        backToSummary: "返回摘要",
        collapse: "收起",
        openArchivedPlan: "从对话打开已归档计划",
        openFile: "打开文件",
        openPlanProgress: ({ title }) => `打开计划与进度：${title}`,
        openSessionActivity: "打开会话活动",
        openTaskUpdates: "打开任务动态",
        retry: "重试",
        retrying: "重试中",
        stop: "停止",
        stopping: "停止中",
        viewDiff: "查看 Diff",
        viewAudit: "查看审计",
        viewFileChanges: "查看文件变更",
        viewResult: "查看结果",
      },
      labels: {
        acceptanceCriteria: "验收标准",
        archivedPlanProgressWorkspace: "已归档计划与进度工作区",
        changedFiles: "变更文件",
        conversation: "对话",
        detailed: "详细",
        details: "详情",
        fileChanges: "文件变更",
        fullResult: "完整结果",
        includesChildTasks: "包含子任务",
        intent: "意图",
        instructions: "说明",
        latestActivity: "最新活动",
        plan: "计划",
        planInteraction: "计划交互",
        planProgress: "计划与进度",
        planProgressWorkspace: "计划与进度工作区",
        planTarget: "计划",
        resultSummary: "结果摘要",
        resizeDetailsPanel: "调整详情面板宽度",
        routerDispatch: "分派",
        routerIntent: "意图",
        routerOutcome: "结果",
        routerScope: "范围",
        selectedTaskTarget: "当前任务",
        sessionActivity: "会话活动",
        sessionTarget: "会话",
        summary: "摘要",
        taskActions: "任务操作",
        taskActivity: "任务动态",
        taskDetails: "任务详情",
        taskInput: "任务输入",
        taskTarget: ({ index }) => `任务 ${index}`,
        userAction: "操作",
        userLabel: "输入",
        userYou: "你",
        workspaceChanges: "工作区变更",
      },
      messages: {
        answerPlaceholder: "在输入框中回答。",
        conversationEmpty: "暂无对话",
        fileCount: ({ count }) => `${count} 个文件`,
        fileCountChanged: ({ count }) => `${count} 个文件已变更。`,
        confirmationResolution: {
          confirmed: "确认已接受。Plato 可以从此任务继续。",
          revise: "已记录修订请求。任务范围输入现在会优化此任务。",
          skipped: "确认已跳过。Plato 不会执行此操作。",
        },
        fullResultAvailable: "完整结果可查看。",
        guidancePlaceholderPlan: "让 Plato 优化整体计划。",
        guidancePlaceholderSession: "描述目标，或为此会话补充指导。",
        guidancePlaceholderTask: "为此任务补充指导。",
        planInteractionBody:
          "输入会优化整个计划。选择某个任务后，可以查看或指导单个任务。",
        sectionsAvailable: ({ count }) => `${count} 个章节可查看。`,
        taskCount: ({ count }) => `${count} 个任务`,
      },
      fileChangeTypes: {
        created: "新增",
        deleted: "删除",
        modified: "修改",
        renamed: "重命名",
      },
      resultSectionKinds: {
        link: "链接",
        list: "列表",
        metric: "指标",
        text: "文本",
      },
      status: {
        auditVerdict: {
          failed: "失败",
          inconclusive: "尚无定论",
          not_available: "不可用",
          passed: "通过",
          warning: "警告",
        },
        confirmation: {
          expired: "已过期",
          pending: "等待",
          resolved: "已确认",
        },
        eventConnection: {
          connected: "事件实时",
          disconnected: "事件离线",
          resyncing: "重新同步中",
        },
        execution: {
          cancelled: "已取消",
          done: "完成",
          failed: "失败",
          not_started: "未开始",
          pending: "排队中",
          running: "运行中",
          unknown: "未知",
          waiting_for_user: "等待",
        },
        messageKind: {
          actionable: "需要回复",
          error: "错误",
          informational: "更新",
          response: "结果",
        },
        planning: {
          assessing: "理解中",
          awaiting_user: "等待用户",
          cancelled: "已取消",
          capturing_input: "记录输入中",
          draft_ready: "草稿就绪",
          empty: "新会话",
          published: "已发布",
          ready_to_plan: "可规划",
          rejected: "已拒绝",
          unknown: "未知",
        },
        readiness: {
          accepted: "已接受",
          cancelled: "已取消",
          draft: "草稿",
          published: "已发布",
          unknown: "未知",
        },
        primaryExecutionRunning: "执行中",
        readOnly: "只读",
        session: {
          completed: "已完成",
          draft_ready: "草稿就绪",
          failed: "失败",
          new: "新会话",
          running: "运行中",
          understanding: "理解中",
          waiting_user: "等待用户",
        },
        stale: "已过期",
        stopping: "停止中",
        taskNode: {
          cancelled: "已取消",
          done: "完成",
          draft: "草稿",
          failed: "失败",
          queued: "排队中",
          running: "运行中",
          waiting_user: "等待",
        },
        taskTree: {
          completed: "已完成",
          draft: "草稿",
          failed: "失败",
          published: "已发布",
          running: "运行中",
        },
      },
    },
    actions: {
      createSession: "新建会话",
      copySessionId: "复制会话 ID",
      deleteSession: "删除会话",
      newSession: "新建",
      openSession: "打开会话",
      publishPlan: "发布计划",
      renameSession: "重命名会话",
      repairAuthoringState: "修复编排状态",
    },
    empty: {
      createFirstSessionBody: "这个工作区还没有会话。准备开始时创建一个会话。",
      createFirstSessionTitle: "创建第一个会话",
      noPlanBody: "描述一个目标。Plato 会先为你起草任务计划。",
      noPlanTitle: "还没有任务计划",
    },
    input: {
      contextMessageAriaLabel: "上下文消息",
      sendMessageAriaLabel: "发送消息",
      writingToPrefix: "写入",
      writingTo: ({ target }) => `写入${target}`,
    },
    interaction: {
      ask: {
        actions: {
          answer: "提交回答",
          answering: "正在提交",
          cancelQuestion: "取消问题",
          cancelling: "正在取消",
          defer: "稍后回答",
          deferring: "正在暂缓",
          submitAllAnswers: "提交全部回答",
          submittingAllAnswers: "正在提交回答",
          viewInConversation: "在会话中查看",
        },
        labels: {
          answerText: "回答内容",
          optional: "可选",
          planningQuestions: "规划问题",
          question: ({ index }) => `问题 ${index}`,
          selectedAnswer: "已选回答",
          selectedOption: "已选择",
          task: ({ title }) => `任务：${title}`,
          taskInputRequired: "任务需要输入",
        },
        messages: {
          addMissingInformation: "补充缺失的信息。",
          addYourAnswer: "填写你的回答。",
          batchAnswerHeader: "批量 ASK 回答：",
          batchAnswerItem: ({ answer, index, question }) =>
            `${index}. ${question}\n回答：${answer}`,
          chooseOption: "提交前请选择一个选项。",
          chooseOptionOrEnterAnswer: "请选择一个选项，或填写回答。",
          enterAnswer: "提交前请填写回答。",
          requiredQuestions: "提交前请回答必填问题。",
          staleAsk:
            "此问题不再匹配当前选中的任务。请刷新，或选择正在等待回答的任务后再提交。",
        },
        statuses: {
          answered: "已回答",
          cancelled: "已取消",
          deferred: "已暂缓",
          expired: "已过期",
          pending: "等待回答",
          superseded: "已被替代",
        },
      },
      confirmation: {
        actions: {
          confirm: "确认",
          resolveDecision: "提交决定",
          resolving: "正在提交",
          reviseTask: "修改任务",
          skip: "跳过",
        },
        labels: {
          confirmationStatus: ({ status }) => `确认${status}`,
          decisionNeeded: "需要决定",
          decisionUnavailable: "决定不可用",
          impact: "影响",
          resolvingDecision: "正在提交决定",
        },
        messages: {
          decisionReadOnly: "此决定已只读。",
          executionWaits: "执行正在等待这个决定。",
          selectOneOption: "请选择一个确认选项。",
        },
        statuses: {
          expired: "已过期",
          pending: "待处理",
          resolved: "已处理",
        },
      },
    },
    labels: {
      noSessions: "暂无会话",
      noSessionSelected: "未选择会话",
      sessionActions: "会话操作",
      sessionName: ({ name }) => `会话：${name}`,
      taskWorkspace: "任务工作区",
      workspaceSessions: "工作区会话",
    },
    plan: {
      defaultTitle: "任务树",
      generatingBody: "Plato 正在理解你的目标，并组织第一版任务计划。",
      generatingTitle: "正在生成任务计划",
      overviewLabel: "计划概览",
      overviewPrepared: "计划概览正在准备中。",
      overviewSummary: ({ count, remainingCount, titles }) => {
        const suffix = remainingCount > 0 ? `，以及另外 ${remainingCount} 个` : "";
        return `包含 ${count} 个任务的计划，覆盖 ${titles}${suffix}。`;
      },
      taskCount: ({ count }) => `此计划包含 ${count} 个任务`,
    },
    repair: {
      authoringStateNeedsRepair: "编排状态需要修复",
      repairing: "修复中",
    },
    sessionDialog: {
      createFormAriaLabel: "新建会话表单",
      createTitle: "新建会话",
      deleteConfirmationAriaLabel: "删除会话确认",
      deleteConfirmationBody: ({ name }) =>
        `删除会话“${name}”？Plato 会归档此会话，并切换到下一个可用会话。`,
      deleteTitle: "删除会话？",
      deleting: "删除中",
      renameFormAriaLabel: "重命名会话表单",
      renameTitle: "重命名会话",
      renaming: "重命名中",
      sessionName: "会话名称",
    },
    states: {
      creatingSession: "创建中",
      creatingSessionFull: "正在创建会话",
      loadError: "加载失败",
      openingSessionBody: "Plato 正在准备这个工作区。",
      openingSessionTitle: "正在打开会话",
      publishingPlan: "正在发布计划",
      unableToOpenSessionBody: "Plato 无法加载此会话。请刷新页面或选择其他会话。",
      unableToOpenSessionTitle: "无法打开会话",
      workspaceSwitchFailed: "无法打开该工作区。",
      workspaceSwitchUnavailable: "工作区切换只能在 Plato 桌面应用中使用。",
      workspaceSwitching: "正在切换工作区。",
    },
  },
  productError: {
    recoveryAriaLabel: "建议的恢复操作",
    recovery: {
      answer_ask: {
        description: "先回答待处理的问题，再继续。",
        label: "回答问题",
      },
      edit_input: {
        description: "修改输入后再次提交。",
        label: "修改输入",
      },
      export_diagnostics: {
        description: "导出已脱敏的诊断包。",
        label: "导出诊断",
      },
      none: {
        description: "当前没有安全的产品恢复操作。",
        label: "无安全恢复操作",
      },
      open_audit: {
        description: "查看受影响会话或任务的审计证据。",
        label: "查看审计",
      },
      open_settings: {
        description: "打开本地 provider 设置。",
        label: "打开设置",
      },
      open_macos_privacy_accessibility: {
        description:
          "打开 macOS 隐私与安全性设置，为 helper 授予辅助功能权限。",
        label: "打开辅助功能权限",
      },
      open_macos_privacy_automation: {
        description:
          "打开 macOS 隐私与安全性设置，为 helper 授予自动化权限。",
        label: "打开自动化权限",
      },
      refresh_snapshot: {
        description: "刷新会话视图以获取最新状态。",
        label: "刷新会话",
      },
      rerun_readiness_check: {
        description: "重新检查本地 computer-use 就绪状态。",
        label: "重新检查就绪状态",
      },
      restart_helper: {
        description: "权限变更后重启 Plato Computer Use Helper。",
        label: "重启 helper",
      },
      retry_command: {
        description: "解决问题后再次运行命令。",
        label: "重试命令",
      },
      retry_task: {
        description: "可重试时重新运行受影响的任务。",
        label: "重试任务",
      },
      wait_for_events: {
        description: "等待 sidecar 事件更新后再继续操作。",
        label: "等待更新",
      },
    },
  },
  usage: {
    actions: {
      openUsage: "用量",
      return: "返回",
    },
    dimensions: {
      plan: "计划",
      session: "会话",
      task: "任务",
      workspace: "工作区",
    },
    dimensionHelp: {
      plan: "显示可归因到当前会话计划的用量。",
      session: "显示此工作区内各会话的总用量。",
      task: "显示可归因到任务的调用用量。",
      workspace: "显示此工作区内所有已记录的 provider 调用。",
    },
    labels: {
      cacheHitRate: "缓存命中率",
      calls: "调用数",
      inputOutput: "输入 / 输出",
      reasoningTokens: "推理 token",
      tokenUsage: "Token 用量",
      tokenUsageBudget: "预算",
      totalTokens: "总 token",
      unknownUsage: "未知用量",
      usage: "用量",
      workspaceId: ({ id }) => `workspace ${id}`,
    },
    messages: {
      compactHelp: "此范围内已记录的 provider 用量。",
      highUsageWarning: "用量偏高",
      highUsageWarningTitle: ({ threshold }) =>
        `此范围已达到至少 ${threshold} tokens。继续长任务前建议先检查用量。`,
      workspaceUsageHelp:
        "按工作区、会话、计划和任务查看 token 用量。这里不会展示原始 prompt 或 completion。",
    },
    states: {
      cacheUnavailable: "缓存不可用",
      noBreakdownRows: "当前筛选下没有明细行。",
      noUsageTracked: "尚未记录 token 用量。",
      notReported: "未报告",
      routeUnavailable: "用量路由不可用",
      routeUnavailableBody: "此路由缺少用量上下文。",
      sidecarRequired: "Token 用量需要本地 sidecar。",
      summaryUnavailable: "Token 用量摘要不可用。",
    },
  },
  settings: {
    actions: {
      configureSettings: "配置设置",
      continueToMainPage: "继续进入主页面",
      closeSettings: "关闭设置",
      exportDiagnostics: "导出诊断",
      exportingDiagnostics: "正在导出诊断",
      openSettings: "打开设置",
      retryCheck: "重新检查",
      retryLoad: "重新加载",
      return: "返回",
      saveAndCheck: "保存并检查",
    },
    fields: {
      apiKey: "API 密钥",
      bundle: "诊断包",
      defaultProfile: "默认配置",
      diagnostics: "诊断",
      gitAvailability: "Git 可用性",
      initializeGitForOpenedWorkspaces: "打开工作区时初始化 Git",
      interfaceLanguage: "界面语言",
      logging: "日志",
      loggingProfile: "日志配置",
      model: "模型",
      provider: "服务商",
      readiness: "就绪状态",
      webFetch: "网页正文读取",
      webFetchMaxCharsPerUrl: "单个 URL 字数上限",
      webFetchMaxTotalChars: "总字数上限",
      webFetchMaxUrls: "URL 数量上限",
      webSearch: "网页搜索",
      webSearchApiKey: "网页搜索 API 密钥",
      webSearchMaxResults: "结果数量",
      webSearchMode: "搜索模式",
      webSearchProvider: "搜索服务商",
      webSearchStatus: "网页搜索状态",
    },
    labels: {
      blockingIssues: "阻塞问题",
      checkingSetup: "正在检查设置",
      completeFirstRunSetup: "完成首次运行设置",
      computerUseAccessibility: "辅助功能已授权",
      computerUseBackend: "Backend",
      computerUseExecutable: "实际执行程序",
      computerUseFailureKind: "失败类型",
      computerUseHelperApp: "Helper 应用",
      computerUseReadiness: "Computer-use 就绪状态",
      computerUseRecoveryActions: "恢复操作",
      computerUseSignature: "Helper 签名",
      computerUseStatus: "状态",
      configured: "已配置",
      degradedReady: "全局设置已就绪，但存在警告。",
      diagnosticsAvailable: "诊断包导出可用",
      diagnosticsUnavailable: "诊断包导出不可用",
      editable: "可编辑",
      firstRun: "首次运行",
      firstRunReady: "首次运行设置已就绪。",
      gitAvailable: "Git 可用",
      gitFailed: "Git 检查失败",
      gitMissing: "未找到 Git",
      localSetup: "全局设置",
      missing: "缺失",
      missingEnvironmentVariables: "缺失的环境变量",
      noDiagnosticSession: "当前还没有可用于导出诊断的会话。",
      notChecked: "未检查",
      notCreated: "未创建",
      readinessIssues: "就绪问题",
      readinessResult: "就绪结果",
      recommendedActions: "建议操作",
      setupCheckUnavailable: "无法检查设置",
      setupRequired: "需要完成设置",
      setupWarning: "设置警告",
      settings: "设置",
      settingsSetupForm: "设置配置表单",
      settingsUnavailable: "设置不可用",
      sidecarRequired: "需要 sidecar",
      webSearchReady: "网页搜索已就绪",
      warnings: "警告",
      workspaceGit: "工作区 Git",
      zipPath: "Zip 路径",
    },
    messages: {
      apiKeyConfigured: ({ source }) =>
        `已通过 ${source} 配置；留空可保持不变。`,
      apiKeyRequired: ({ hint }) => `必填：${hint}。`,
      checkingReadiness: "正在检查就绪状态。",
      checkingSidecarReadiness: "正在检查本地 sidecar 就绪状态。",
      checkingGitAvailability: "正在检查 Git 可用性。",
      diagnosticExportFailed: "诊断导出失败。",
      diagnosticExportHelp:
        "当设置仍失败且已有会话时，导出已脱敏的本地诊断包。",
      gitAvailable: ({ version }) =>
        `Git 可用：${version.replace(/^git version\s*/iu, "")}`,
      gitFailedHelp: "Plato 无法确认此设备上的 Git 是否可用。",
      gitMissingHelp: "安装 Git 后才能为新打开的工作区自动初始化仓库。",
      initializeGitForOpenedWorkspacesHelp:
        "开启后，Plato 会在打开或切换到普通文件夹时运行 git init，并把 .plato/ 写入仓库本地排除文件。",
      loadingSettings: "正在加载设置",
      loadingSettingsHelp: "正在加载本地 sidecar 设置。",
      localSetupReadyWithWarnings: "全局设置已就绪，但存在警告。",
      noReadinessReport: "本地 sidecar 未返回就绪报告。",
      noDiagnosticSession: "当前还没有可用于导出诊断的会话。",
      readinessRecheckFailed: "就绪状态重新检查失败。",
      saveFailed: "设置保存失败。",
      saved: "设置已保存。",
      saving: "正在保存设置。",
      settingsContractUnavailable: "本地 sidecar 未返回设置配置合同。",
      settingsDescription: "配置 Plato 全局本地 LLM 设置；该配置会跨工作区生效。",
      settingsUnavailableHelp:
        "请以本地 sidecar HTTP 模式启动 Plato 后再编辑 Product 1.0 设置。",
      setupRequiredBody:
        "Plato 需要本地 LLM 配置后才能运行主页面工作流。",
      webSearchApiKeyConfigured: ({ source }) =>
        `已通过 ${source} 配置；留空可保持不变。`,
      webSearchApiKeyRequired: ({ hint }) => `开启时必填：${hint}。`,
      webFetchDescription:
        "允许执行 Agent 从选定的公开来源 URL 中读取有界正文。",
      webSearchDescription:
        "允许执行 Agent 搜索当前公开来源，并作为外部证据记录。",
      workspaceGitDesktopUnavailable:
        "工作区 Git 初始化仅在 Plato 桌面应用中可用。",
    },
    localeOptions: {
      "en-US": "English",
      "zh-CN": "简体中文",
    },
    recovery: {
      answer_ask: "回答待处理的问题。",
      edit_input: "编辑当前输入。",
      export_diagnostics: "导出已脱敏的诊断包。",
      none: "没有可用的恢复操作。",
      open_audit: "查看审计证据。",
      open_settings: "配置本地 provider 设置。",
      open_macos_privacy_accessibility: "打开 helper 的 macOS 辅助功能权限。",
      open_macos_privacy_automation: "打开 helper 的 macOS 自动化权限。",
      refresh_snapshot: "完成配置变更后重试。",
      rerun_readiness_check: "重新检查本地 computer-use 就绪状态。",
      restart_helper: "重启 Plato Computer Use Helper。",
      retry_command: "完成配置变更后重试。",
      retry_task: "重试受影响的任务。",
      wait_for_events: "等待 sidecar 事件后再重试。",
    },
    tabs: {
      configuration: "配置",
      dataManagement: "数据管理",
      runtimeBehavior: "运行时行为",
      usageInformation: "使用信息",
    },
  },
  workspace: {
    actions: {
      archiveWorkspace: "归档工作区",
      cancelDelete: "取消",
      confirmDeletePlatoData: "删除 Plato 数据",
      deletePlatoData: "删除 Plato 数据",
      openWorkspaceMenu: "打开工作区操作",
      openOrAddWorkspace: "打开或添加工作区",
      restoreWorkspace: "恢复工作区",
      workspaceManagement: "工作区管理",
    },
    labels: {
      activeWorkspaces: "活跃工作区",
      archived: "已归档",
      archivedWorkspaces: "已归档工作区",
      dataManagement: "数据管理",
      deletePlatoData: "删除 Plato 数据",
      workspace: "工作区",
      workspaceManagement: "工作区管理",
      workspaces: "工作区",
    },
    messages: {
      archiveHelp: "归档会从主页面隐藏工作区，但不会删除文件。",
      bridgeUnavailable: "工作区管理仅在 Plato 桌面应用中可用。",
      deletePlatoDataConfirmation: ({ name }) =>
        `删除 ${name} 的 Plato 数据？项目文件和工作区文件夹会保留。`,
      deletePlatoDataHelp:
        "删除 Plato 产生的 .plato 数据和历史元数据目录，不会删除项目文件。",
      lifecycleActionFailed: "工作区操作失败。",
      loadingWorkspaces: "正在加载工作区。",
      noArchivedWorkspaces: "暂无已归档工作区。",
      noWorkspaceData: "暂无工作区数据。",
      restoreHelp: "恢复后，该工作区会重新显示。",
    },
  },
  workspaceInspection: {
    actions: {
      openFile: "打开文件",
      refresh: "刷新",
      return: "返回",
      viewDiff: "查看 Diff",
    },
    labels: {
      captured: "已捕获",
      changed: "变更",
      changedFiles: "变更文件",
      clean: "干净",
      diff: "Diff",
      fileContent: "文件内容",
      file: "文件",
      fileDiff: "文件 Diff",
      fileViewer: "文件查看器",
      gitStatus: "Git 状态",
      inspectionViews: "检查视图",
      live: "实时",
      localToolFiles: "本地工具文件",
      mixed: "混合",
      repository: "仓库",
      staged: "已暂存",
      truncated: "已截断",
      unstaged: "未暂存",
      untracked: "未跟踪",
      workspaceInspection: "工作区检查",
    },
    states: {
      cleanBody: "此工作区没有变更文件。",
      diffUnavailable: ({ reason }) => `Diff 不可用：${reason}。`,
      diffUnavailableTitle: "Diff 不可用",
      fileUnavailable: ({ reason }) => `文件无法以文本形式渲染：${reason}。`,
      fileUnavailableTitle: "文件不可用",
      inspectionFailed: "工作区检查失败。",
      inspectionUnavailable: "检查不可用",
      inspectionRouteUnavailable: "检查路由不可用",
      inspectionRouteUnavailableBody: "此路由缺少检查上下文。",
      loading: "正在加载工作区检查结果",
      localNoiseSuppressed: ({ count }) =>
        `已隐藏 ${count} 个本地系统文件，不在检查列表中显示。`,
      readOnly: "只读工作区检查。",
      requiresSidecar: "工作区检查需要本地 sidecar。",
      statusUnavailable: "状态不可用。",
    },
  },
};
